version: '3'
services:
  postgresql:
    image: 'postgres'
    environment: 
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=prosa-api-dev-db
    ports:
      - 5432:5432